# Generated by Django 4.2.3 on 2023-07-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('name', models.TextField(max_length=40)),
                ('sales', models.IntegerField()),
                ('expire_date', models.DateTimeField()),
            ],
        ),
    ]
