# Generated by Django 4.2.3 on 2023-07-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0008_alter_product_perishable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='perishable',
            field=models.BooleanField(default=True),
        ),
    ]
